### ISSUE TITLE
请问图片放什么文件夹中

### ISSUE THREAD

**Issue by ityulong** [Knn120/OnJava8-PDF#1]
因为我转换出来的PDF没有图片，图片要放在特定的文件夹中吗

**Comment by Knn120** [comment]
这个需要根据 你 md文件中 引用图片的路径来存放图片.
比如 我的 md文件中 一个 图片引用路径为  ![database-split-horizon](images/database-split-horizon.png)
则 只需要 将图片放在 images 这个文件夹中, images 这个文件夹 和 转换的  python脚本在同一级目录即可!

**Comment by Knn120** [comment]
> 因为我转换出来的PDF没有图片，图片要放在特定的文件夹中吗

@ityulong 这个需要根据 你 md文件中 引用图片的路径来存放图片.
比如 我的 md文件中 一个 图片引用路径为 images/database-split-horizon.png
则 只需要 将图片放在 images 这个文件夹中, images 这个文件夹 和 转换的 python脚本在同一级目录即可!
