### ISSUE TITLE
On-Java-8_Zh_latest.pdf 包含英文目录，可以只留中文目录吗

### ISSUE THREAD

**Issue by Vixb1122** [Knn120/OnJava8-PDF#5]
![image](https://user-images.githubusercontent.com/17810492/109783278-c5052080-7c44-11eb-9b10-4af9e60608b2.png)

**Comment by Knn120** [comment]
已解决

**Comment by Knn120** [comment]
@Vixb1122 已解决

**Comment by Vixb1122** [comment]
@Knn120 建议取消目录里面最外层的书名目录，目录直接从简介开始
![image](https://user-images.githubusercontent.com/17810492/110190273-78486200-7e5d-11eb-9c12-44930ffb64c3.png)

**Comment by Knn120** [comment]
> @Knn120 建议取消目录里面最外层的书名目录，目录直接从简介开始
> ![image](https://user-images.githubusercontent.com/17810492/110190273-78486200-7e5d-11eb-9c12-44930ffb64c3.png)

已修改

**Comment by Knn120** [comment]
> > @Knn120 建议取消目录里面最外层的书名目录，目录直接从简介开始
> > ![image](https://user-images.githubusercontent.com/17810492/110190273-78486200-7e5d-11eb-9c12-44930ffb64c3.png)
> 
> 已修改

@Vixb1122
