### ISSUE TITLE
求一份英文md

### ISSUE THREAD

**Issue by yuejin66** [Knn120/OnJava8-PDF#8]
你好作者大大，可以发一份英文版md到我的邮箱吗？万分感谢！13727764936@163.com

**Comment by Knn120** [comment]
> 你好作者大大，可以发一份英文版md到我的邮箱吗？万分感谢！[13727764936@163.com](mailto:13727764936@163.com)

目录里面有, On-Java-8_En.pdf 这个就是

**Comment by yuejin66** [comment]
那个pdf太难看了。。。想要个md自己渲染着看。

**Comment by yuejin66** [comment]
感谢回复，如果不方便就算了，我再找找，再次感谢回复！

**Comment by Knn120** [comment]
> 那个pdf太难看了。。。想要个md自己渲染着看。

好的 我找下 因为很久了 不一定能找到  找到的话 发你邮箱

**Comment by ajf12f** [comment]
> > 那个pdf太难看了。。。想要个md自己渲染着看。
> 
> 好的 我找下 因为很久了 不一定能找到 找到的话 发你邮箱

如果可以的话，帮忙发一份 pooy@ pooy.net
